name: Delete All Bot Commands on All Servers

on:
  workflow_dispatch:

jobs:
  delete-bot-commands:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and restart updated discord bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          envs: DISCORD_TOKEN, DISCORD_CLIENT_ID
          script: |
            cd freeBrunch-discord-bot
            git stash && git pull origin main
            npm install
            export DISCORD_TOKEN=$DISCORD_TOKEN && export DISCORD_CLIENT_ID=$DISCORD_CLIENT_ID && node delete-all-commands-global.js