name: Deploy Discord Bot to Dev

on:
  workflow_dispatch:
  push: 
    branches: dev
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

jobs:
  deploy-bot:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and restart updated discord dev bot
        env:
          DISCORD_DEV_TOKEN: ${{ secrets.DISCORD_DEV_TOKEN }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          envs: DISCORD_DEV_TOKEN
          script: |
            cd freeBrunch-discord-bot-dev
            git stash && git pull origin dev
            npm install
            export DISCORD_DEV_TOKEN=$DISCORD_DEV_TOKEN && export NODE_ENV=development && pm2 restart freeBrunch-bot-dev --update-env
