name: Deploy Discord Bot to Production

on:
  workflow_dispatch:
  push: 
    branches: main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

jobs:
  deploy-bot:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and restart updated discord bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          envs: DISCORD_TOKEN
          script: |
            cd freeBrunch-discord-bot
            git stash && git pull origin main
            npm install
            export DISCORD_TOKEN=$DISCORD_TOKEN && export NODE_ENV=production && pm2 restart freeBrunch-bot --update-env
