name: Deploy Discord Bot

on:
  workflow_dispatch:
  push: 
    branches: main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

jobs:
  deploy-bot:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and restart updated discord bot
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /freebrunch-discord-bot
            git pull origin master
            npm install
            pm2 restart freeBrunch-bot
            echo "Bot restarted"