name: Deploy Bot Commands to All Servers

on:
  workflow_dispatch:

jobs:
  deploy-bot:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and restart updated discord bot
        uses: appleboy/ssh-action@master
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          envs: DISCORD_TOKEN, DISCORD_CLIENT_ID
          script: |
            cd freeBrunch-discord-bot
            git stash
            git pull origin main
            npm install
            node deploy-commands-global.js