name: Deploy Discord Bot Commands to Dev Server

on:
  workflow_dispatch:

jobs:
  deploy-bot:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and restart updated discord bot
        uses: appleboy/ssh-action@master
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
          DISCORD_DEV_GUILD_ID: ${{ secrets.DISCORD_DEV_GUILD_ID }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          envs: DISCORD_TOKEN, DISCORD_CLIENT_ID, DISCORD_DEV_GUILD_ID
          script: |
            cd freeBrunch-discord-bot
            git pull origin main
            npm install
            node deploy-commands-dev.js