name: Deploy Discord Bot

on:
  workflow_dispatch:
  push: 
    branches: main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

jobs:
  deploy-bot:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and restart updated discord bot
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd freeBrunch-discord-bot
            git pull origin main
            npm install
            pm2 restart freeBrunch-bot
