name: Kill Discord Bot on Production

on:
  workflow_dispatch:

jobs:
  kill-bot:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and stop discord bot
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            pm2 stop freeBrunch-bot