name: Deploy Discord Bot to Self Hosted Runner

on:
  workflow_dispatch:
  push: 
    branches: main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

jobs:
  deploy-bot:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Install Dependencies
        run: |
          npm install
          npm install pm2@latest -g
      - name: Start Bot with PM2
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: |
          pm2 restart freeBrunch-Discord-Bot || pm2 start index.js --name "freeBrunch-Discord-Bot" -- start