name: Deploy to Self Hosted Runner

on:
  workflow_dispatch:
  push: main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Start Bot with PM2
        run: |
          pm2 stop all
          export DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          pm2 start index.js --name freebrunch-discord-bot
